### ISSUE TITLE
Input file format

### ISSUE THREAD

**Issue by sudhirjadhao** [jhkorhonen/MOODS#17]
Hi,
I am trying to run MOODS with pwm file,. It gives below error

moods_dna.py: error: could not parse matrix file HNF6_MOUSE.H11MO.0.A.pwm

Command used:

~/Tools/MOODS-python-1.9.3/scripts/moods_dna.py -S HNF6_MOUSE.H11MO.0.A.pwm -s ~/Database/Mouse/mm10/mm10.fasta -p 0.0001

Input file format:

0.007870731351891107    -0.5026745162600582     -0.6426579251897485     0.6212723643415664
-0.8233170879861396     -0.22997490888551764    -0.10839091463378318    0.6255086957304884
-1.770121075237143      -0.3458284352918658     -0.43940523421984795    0.9073041393368604
1.3690370491215165      -3.324736791140142      -4.400058040447161      -3.903141843818025
-3.572690530904845      -4.400058040447161      -2.9606438896517475     1.362989297771286
-2.9606438896517475     -0.4642346826548472     -3.572690530904845      1.191348924768384
-3.572690530904845      -4.400058040447161      1.3730486588530793      -4.400058040447161
1.371044865612529       -3.903141843818025      -4.400058040447161      -3.572690530904845
-3.324736791140142      -2.4841943814369576     -3.572690530904845      1.3487339948893322
-3.9031418438180254     0.2503417686541541      -2.8186351867496584     0.9691373831245766
-0.55634002882743       -0.598567918596995      0.18027335610535977     0.518528091684519

Can you please tell me where I am going wrong ?

**Comment by jhkorhonen** [comment]
The files should follow the JASPAR format conventions, as explained in the wiki (https://github.com/jhkorhonen/MOODS/wiki/Getting-Started). You'll need to transpose your files, i.e. each row corresponds to the scores of single nucleotide (in the order A, C, G, T).

**Comment by sudhirjadhao** [comment]
I transpose my input,  but still its showing same error.

Update Input:

0.007870731 -0.823317088 -1.770121075 1.369037049 -3.572690531 -2.96064389 -3.572690531 1.371044866 -3.324736791 -3.903141844 -0.556340029
-0.502674516 -0.229974909 -0.345828435 -3.324736791 -4.40005804 -0.464234683 -4.40005804 -3.903141844 -2.484194381 0.250341769 -0.598567919
-0.642657925 -0.108390915 -0.439405234 -4.40005804 -2.96064389 -3.572690531 1.373048659 -4.40005804 -3.572690531 -2.818635187 0.180273356
0.621272364 0.625508696 0.907304139 -3.903141844 1.362989298 1.191348925 -4.40005804 -3.572690531 1.348733995 0.969137383 0.518528092

Note: Motif name HNF6
Source of matrix: http://hocomoco11.autosome.ru/motif/HNF6_MOUSE.H11MO.0.A

**Comment by jhkorhonen** [comment]
Copy-pasting that into a file definitely works for me. Can you attach the actual file?

(Looks like parser may not like it if there are too many newlines after the data, so that may be the issue. I'm making a note to myself to fix this in future releases.)

**Comment by sudhirjadhao** [comment]
Thank you for your time.

Please find attached file for your reference
[hnf6_motif3.zip](https://github.com/jhkorhonen/MOODS/files/1320547/hnf6_motif3.zip)


Best Regards,
Sudhir

**Comment by jhkorhonen** [comment]
Please include an unzipped version of the file, my unzip doesn't like whatever version of zip you are using.
