### ISSUE TITLE
Py3, Python extension? Where does the Python extension <count_log_odds> go?

### ISSUE THREAD

**Issue by zhenyisong** [jhkorhonen/MOODS#21]
I used the conda to install the python3 version. However, I tried to call the method I once used in py2, for example, count_log_odds, reverse_complement etc., and found they were all gone. I think you may design a new interface ([here is your link for these python extensions)](https://www.cs.helsinki.fi/group/pssmfind/doc/python/MOODS.html)?

I checked the post by @jenzopr , he used this method MOODS.parsers.pfm_to_log_odds, but this seemed to need a pfm file first. I also check the MOODS dir (python3.6/site-packages/MOODS
) and no corresponding expected modules. Then I figured that all I have to do is to rewrite my old code?

So, do I miss something here? Or I have to install some other version (downplay?) to continue my old way and use old method. Any suggestions if greatly appreciated.

**Comment by jhkorhonen** [comment]
There's now a very rudimentary [function reference](https://github.com/jhkorhonen/MOODS/wiki/Function-reference) on the wiki.
