### ISSUE TITLE
installation MOODS-python-1.9.3

### ISSUE THREAD

**Issue by RafaelMViana** [jhkorhonen/MOODS#24]
Hi,

I want to install MOODS 1.9.3 as python module in order to run the suite HINT
I am using python 2.7 and the C++ compiler g++5- version:5.5.0

I follow the github guidelines, and get a problem during installation
tar xzvf MOODS-python-1.9.3.tar.gz
cd MOODS-python-1.9.3/
sudo python setup.py install

running install
running build
running build_py
running build_ext
building 'MOODS._tools' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 
-g -fdebug-prefix-map=/build/python2.7-3hk45v/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Icore/ -I/usr/include/python2.7 
-c core/tools_wrap.cxx -o build/temp.linux-x86_64-2.7/core/tools_wrap.o -march=native -O3 -fPIC --std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
core/tools_wrap.cxx:171:11: fatal error: Python.h: No such file or directory
 # include <Python.h>
           ^~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

I see that under the core folder there are xxx.h files without python.h

There is a path to build/lib.linux-x86_64-2.7/MOODS/ with some .py files
on the other hand, build/temp.linux-x86_64-2.7/core/ is empty

May you point me out what I am doing wrong?

Kind regards

**Comment by jhkorhonen** [comment]
You probably don't have headers and libraries for python development installed on your system. Install `python-dev` or similar package from your package manager, depending on your Linux distro.
