### ISSUE TITLE
Failure to install under python3

### ISSUE THREAD

**Issue by jonwells90** [jhkorhonen/MOODS#3]
Hey, haven't been able to properly install MOODs using python3 (3.5).

After:
python3 setup.py install
I get the following error:
cport.cc:232:9: error: use of undeclared identifier 'Py_InitModule'
        (void) Py_InitModule("_cmodule", SpamMethods);

having a look at the Python3 documentation seems to suggest that the issue might be due to Py_InitModule not being used by python3.x anymore.
maybe see: http://stackoverflow.com/questions/28305731/compiler-cant-find-py-initmodule-is-it-deprecated-and-if-so-what-should-i

**Comment by jhkorhonen** [comment]
The 1.x release of MOODS does not support python3. This might be remedied in the 2.x branch -- later this year hopefully -- as it is moving to SWIG-generated scripting language bindings, so it should be fairly easy to also generate python3 bindings.
