### ISSUE TITLE
[install,bug] setup.py contain files that are not in master branch

### ISSUE THREAD

**Issue by shouldsee** [jhkorhonen/MOODS#30]
# 'core/tools_wrap.cxx', ### not in master branch
                           # 'core/scan_wrap.cxx', ### not in master branch
                           # 'core/parsers_wrap.cxx',

**Comment by jhkorhonen** [comment]
The `.cxx` files are autogenerated by Swig and not kept in the repository. See [Wiki/Development](https://github.com/jhkorhonen/MOODS/wiki/Development) for details.

For installing MOODS, use the latest release tarball or install from PyPi, under "Download" section on the repository front page.
