### ISSUE TITLE
Cannot install on python 3.8.2

### ISSUE THREAD

**Issue by gintarebucaite** [jhkorhonen/MOODS#32]
Hi,

I've tried to install Moods via Conda, however, it says that Python 3.8 is not supported.

Error message:
```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - moods -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']

Your python: python==3.8.2=h8356626_5_cpython

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
```

Could you please add support for python 3.8?

Thank you!

**Comment by jhkorhonen** [comment]
The version requirements are set in the Conda package, as MOODS itself works on fine on python 3.9. In fact, it looks like Bioconda as a whole only supports python 3.6 and 3.7: https://bioconda.github.io/user/versions.html

As Bioconda packages are maintained by the Bioconda team, I unfortunately cannot help with this. However, you can install MOODS from pip or source for python 3.9:

    pip install --user MOODS-python

See the wiki for more details: https://github.com/jhkorhonen/MOODS/wiki/Installation
