### ISSUE TITLE
Is this package still being maintained?

### ISSUE THREAD

**Issue by laserson** [jhkorhonen/MOODS#34]
Based on the GitHub repo, it looks like MOODS hasn't really been touched in a couple years. Have the development efforts stopped? Is there an alternative tool that is more actively being developed?

**Comment by jhkorhonen** [comment]
I still follow Github issues and do basic maintenance as needed.

The current version is essentially feature-complete and there are no outstanding bugs, so there haven't been any updates for a few years. There's some cleanup work that probably should be done at some point, but it keeps getting buried under an ever-increasing pile of uncompleted todo items...
