### ISSUE TITLE
Is there a way to write results to output file progressively

### ISSUE THREAD

**Issue by alexlenail** [jhkorhonen/MOODS#37]
I'm running out of memory trying to scan the human reference genome chr1, somewhere in the ~500GB RAM range. I've noticed that `moods-dna.py` seems to try to scan the whole chromosome before writing anything to the csv. Is there a way to flush the buffer?

**Comment by jhkorhonen** [comment]
There is no such feature implemented in `moods_dna.py`, but in principle this is not too hard to implement with some custom Python scripting.

However, the behaviour sounds extremely strange – `moods_dna.py` should work in most cases fine with chromosome-length sequences on desktop machines. Could you try either stricter thresholds for hit reporting (low p-value or higher absolute threshold), or using the `--no-snps` option, and see what happens?

**Comment by alexlenail** [comment]
Thanks @jhkorhonen  

I set the p-value as 0.001, rather than the default 0.0001 -- that's probably why.

**Comment by alexlenail** [comment]
If I do 
```
scanner = MOODS.scan.Scanner(7)
scanner.set_motifs(matrices, bg, thresholds)
motif_matches = scanner.scan(dna)
```
do I not scan the sequence with the reverse complements of the matrices (i.e. scan the reverse complement of the sequence) by default? It seems like `moods-dna.py` creates the reverse complement matrices by default. 

https://github.com/jhkorhonen/MOODS/blob/568b8fcfd781af14a505743206dd05923e6cc954/python/scripts/moods-dna.py#L232-L238

**Comment by jhkorhonen** [comment]
You'll need to generate the reverse complement matrices as in that snippet and add them to the matrix list. See also `ex-basic-usage.py` script for help with the basic workflow.

You may also find `ex-scanner.py` useful if you are wanting to split your input files into multiple parts for scanning, as per your original question.
