### ISSUE TITLE
`--p-value 0.001` returns motif matches with negative scores

### ISSUE THREAD

**Issue by alexlenail** [jhkorhonen/MOODS#39]
If I'm understanding correctly, the scores MOODS reports are log odds that the PWM generated the sequence over the background. A sequence with a log odds score of 0 has equal probability of having been generated by the PWM model or the background distribution. 

Running MOODS with a p-value threshold of 0.001 should only return sequences 1000x more likely to come from the PWM model than the background. So I'm confused as to why, when you scan with `--p-value 0.001`, you get hits with negative scores -- which should indicate a sequence is likelier to come from the background model than the PWM, right?

**Comment by jhkorhonen** [comment]
The p-value threshold, as explained [here](https://github.com/jhkorhonen/MOODS/wiki/Brief-theoretical-introduction), corresponds to taking the best scoring _p_ fraction of the probability mass according to the background distribution. In other words, with p-value _p_ you would expect to get about _p_ times the length of the sequence hits.

If you instead want matches as per your question, you can use `--threshold` to directly set threshold to a specific value. For example, `--threshold 3 --log-base 10` (or `--threshold 6.91`, if you prefer)  would give you sequences where the probability of the PWM generating the sequence is at least 1000x the probability of the background generating the sequence. Note that you can set the assumed background sequence frequencies with `--lo-bg` option.

**Comment by alexlenail** [comment]
Thanks for getting back @jhkorhonen,
Just to close the loop, it seems like when PFMs have many zero entries, the number of sequences likelier under the PWM than under the background is a small fraction of the space of random sequences.
