### ISSUE TITLE
install MOODS python extention module for python3

### ISSUE THREAD

**Issue by joshuabhk** [jhkorhonen/MOODS#4]
Hello,

First thank you very much for your great module! Your work helped me a lot!
But when I tried to move onto python3, the python interface cannot be built. It is not your bug but python's change of module extension rules.
https://docs.python.org/3/howto/cporting.html
If you can port for python3 that would be great! If you do not have time, I might chip in!

Thanks.

Bong-Hyun

**Comment by jhkorhonen** [comment]
This should be fixed already in `develop` branch version, though I have not tested that the new SWIG-generated python interfaces actually work also with python3 as promised. The `develop` branch is also already in a state where it could be used to replace MOODS 1.0, though using it will require some edits to the calling scripts at the moment -- the development has been really sluggish, unfortunately.

I'll try to put up a semi-usable beta package ("version 1.9") of the new python interfaces later this week, assuming I can find the time to do that properly.

If you are feeling particularly adventurous, you can try using the current `develop` head (3ed3c010da06064761d777f747be2ba8361af1cb). You'll need SWIG 3 installed (try `swig -version`), but assuming you have that, you can just symlink/copy the `MOODS/core/` under `MOODS/python/` and run `build.sh` under `MOODS/python/` to compile everything. The example scripts won't necessarily work with python3 directly, but should get you started.

**Comment by joshuabhk** [comment]
Thank you so much for your help!! I will try and let you know the result.

Best,

Bong-Hyun

**Comment by jhkorhonen** [comment]
There's now a cleanly packaged 1.9 release, though I have not yet had time to test it with python3.

**Comment by jhkorhonen** [comment]
For reference, everything should be Python 3 compatible as of version 1.9.3.
