### ISSUE TITLE
MOODS 1.9.0- problem running example 

### ISSUE THREAD

**Issue by mazrooei** [jhkorhonen/MOODS#5]
Hi,

I installed MOODS 1.9.0 and tried to run the example like you mentioned : 
python ex-basic-usage.py example-data/seq/chr1-5k-55k.fa example-data/matrices/ 
I got "Illegal instruction (core dumped)" error at line "bg = MOODS.tools.bg_from_sequence_dna(seq,1)"

Also, I tried to test MOODS 1.9.0 using "example1.py" sample in the "examples" folder you had in the previous versions. Again, I got an error on the line which calls function "MOODS.search()". The exact error is: "AttributeError: 'module' object has no attribute 'search' "

Could you tell me what the problem is?

Thank you in advance.

**Comment by jhkorhonen** [comment]
Please let me know your OS, python version and C++ compiler. Also attach complete compilation and run logs so I can see if there is anything obviously wrong with them. 

As for the latter question, the new interface is slightly different from the old one, so the old examples will not work.

**Comment by mazrooei** [comment]
Hi,
It seems that the problem was with finding the package. I solved it by adding these lines at the very beginning:
import sys
sys.path.insert(0,"ADDRESS/MOODS/1.9.0") 

Thanks!
----
P.S. FYI
OS Linux
python version 2.7.3
g++ (GCC) 4.4.7

**Comment by jhkorhonen** [comment]
Yeah, you need the `MOODS/` directory to be in `sys.path`. The latest release documentation should make this more clear, and the `setup.py` should again work correctly for `python setup.py install`.

**Comment by YichaoOU** [comment]
having the same problem here: `Illegal instruction `

What is the solution?

**Comment by jhkorhonen** [comment]
Please let me know your OS, python version and C++ compiler. Please also do a clean installation using one of the methods described on the [wiki](https://github.com/jhkorhonen/MOODS/wiki/Installation), and attach complete compilation and run logs so I can see if there is anything obviously wrong with them.

**Comment by YichaoOU** [comment]
the latest version 1.9.4.1.

I was able to solve the problem rolling back to 1.9.3.
